all:
	g++ ./prog.cpp -o ./prog -I/home/jbu/Dropbox/research/workspace/testjna/so/include -I${JPEG_LIB_DIR}/include -L/home/jbu/Dropbox/research/workspace/testjna/so/lib -L${JPEG_LIB_DIR} -lmemfxns -ljpeg

clean:
	rm ./prog
